file_format: "1"
id: dactyl_manuform_5x6
name: Dactyl Manuform
type: shield
url: https://github.com/ricardo-re-azevedo/zmk-config-dactyl-manuform
requires: [pro_micro]
features:
  - keys
siblings:
  - dactyl_manuform_5x6_left
  - dactyl_manuform_5x6_right